In [11]:
import os
import numpy as np
import matplotlib as mp
import matplotlib.pyplot as plt
import pandas as pd

data = pd.read_csv("./dist_renta_hogares.csv",delimiter=";")

In [12]:
display(data)

,Municipios,Distritos,Secciones,Sexo,Nacionalidad,Distribución de la renta por unidad de consumo,Periodo,Total
0,32001 Allariz,NaN,NaN,Total,Española,Población con ingresos por unidad de consumo p...,2023,.
1,32001 Allariz,NaN,NaN,Total,Española,Población con ingresos por unidad de consumo p...,2022,.
2,32001 Allariz,NaN,NaN,Total,Española,Población con ingresos por unidad de consumo p...,2021,.
3,32001 Allariz,NaN,NaN,Total,Española,Población con ingresos por unidad de consumo p...,2020,.
4,32001 Allariz,NaN,NaN,Total,Española,Población con ingresos por unidad de consumo p...,2019,.
...,...,...,...,...,...,...,...,...
78727,32092 Vilariño de Conso,3209201 Vilariño de Conso distrito 01,3209201001 Vilariño de Conso sección 01001,Mujeres,Extranjera,Población con ingresos por unidad de consumo p...,2019,.
78728,32092 Vilariño de Conso,3209201 Vilariño de Conso distrito 01,3209201001 Vilariño de Conso sección 01001,Mujeres,Extranjera,Población con ingresos por unidad de consumo p...,2018,.
78729,32092 Vilariño de Conso,3209201 Vilariño de Conso distrito 01,3209201001 Vilariño de Conso sección 01001,Mujeres,Extranjera,Población con ingresos por unidad de consumo p...,2017,.
78730,32092 Vilariño de Conso,3209201 Vilariño de Conso distrito 01,3209201001 Vilariño de Conso sección 01001,Mujeres,Extranjera,Población con ingresos por unidad de consumo p...,2016,.
78731,32092 Vilariño de Conso,3209201 Vilariño de Conso distrito 01,3209201001 Vilariño de Conso sección 01001,Mujeres,Extranjera,Población con ingresos por unidad de consumo p...,2015,.

**Vamos a ver las columnas que tienen nulos**

In [13]:
print("¿Tiene nulos?")
cols_null = []

for i in data.columns:
    nulo = np.any(data[i].isna())
    
    print(f"{i} -> {np.where(nulo, 'Si', 'No')}")
    
    [cols_null.append(i) if nulo else None] # guardamos los nombres de las columnas para estudiarlas

print("\n")
print("\nConteo de valores únicos\n")

for i in data.columns:
    if i in cols_null:
        unic = data[i].drop_duplicates()
        print(f"{i} - {unic.count()} - {data[i].dtype}")
        cont = 0
        # for j in unic:
        #     print(j)            
        #     if cont < 100: cont += 1
        #     else: break


print("\n- Viendo los resultados podemos deducir que son columnas no categorizables -")
print("- \"Total\" es la única columna que podemos hacer la media para rellenar los nulos *Además hay que limpiar el carácter \".\" que impide que se haga la media-")

# Quitamos los nulos de Distritos y Secciones

data.Distritos = data.Distritos.fillna("No")
data.Secciones = data.Secciones.fillna("No")

# Quitamos los nulos de Total con la media de las celdas con valor numérico y entendemos que los . son el valor 0

mascara_punto = data.Total == "."
index_puntos = data.Total[mascara_punto]
mascara_nulo = data.Total == None
index_nulos = data.Total[mascara_nulo]

print("- Total puntos en [Col. Total] -> ", index_puntos.count())
print("- Total nulos en [Col. Total] -> ", index_nulos.count())

data.Total = data.Total.replace(",", ".", regex=True) # reemplazamos las , por .
data['Total'] = data['Total'].replace('^\\.$', 0, regex=True) # con regex cambiamos los . solitarios por valor 0 (esto si lo he mirado en la IA)
data.Total = data.Total.astype(float) # convertimos la columna en float
data.Total = data.Total.fillna(data.Total.mean().__round__(2)) # rellenamos los nulos con el valor medio

display(data)

¿Tiene nulos?
Municipios -> No
Distritos -> Si
Secciones -> Si
Sexo -> No
Nacionalidad -> No
Distribución de la renta por unidad de consumo -> No
Periodo -> No
Total -> Si



Conteo de valores únicos

Distritos - 127 - object
Secciones - 267 - object
Total - 656 - object

- Viendo los resultados podemos deducir que son columnas no categorizables -
- "Total" es la única columna que podemos hacer la media para rellenar los nulos *Además hay que limpiar el carácter "." que impide que se haga la media-
- Total puntos en [Col. Total] ->  75330
- Total nulos en [Col. Total] ->  0

,Municipios,Distritos,Secciones,Sexo,Nacionalidad,Distribución de la renta por unidad de consumo,Periodo,Total
0,32001 Allariz,No,No,Total,Española,Población con ingresos por unidad de consumo p...,2023,0.0
1,32001 Allariz,No,No,Total,Española,Población con ingresos por unidad de consumo p...,2022,0.0
2,32001 Allariz,No,No,Total,Española,Población con ingresos por unidad de consumo p...,2021,0.0
3,32001 Allariz,No,No,Total,Española,Población con ingresos por unidad de consumo p...,2020,0.0
4,32001 Allariz,No,No,Total,Española,Población con ingresos por unidad de consumo p...,2019,0.0
...,...,...,...,...,...,...,...,...
78727,32092 Vilariño de Conso,3209201 Vilariño de Conso distrito 01,3209201001 Vilariño de Conso sección 01001,Mujeres,Extranjera,Población con ingresos por unidad de consumo p...,2019,0.0
78728,32092 Vilariño de Conso,3209201 Vilariño de Conso distrito 01,3209201001 Vilariño de Conso sección 01001,Mujeres,Extranjera,Población con ingresos por unidad de consumo p...,2018,0.0
78729,32092 Vilariño de Conso,3209201 Vilariño de Conso distrito 01,3209201001 Vilariño de Conso sección 01001,Mujeres,Extranjera,Población con ingresos por unidad de consumo p...,2017,0.0
78730,32092 Vilariño de Conso,3209201 Vilariño de Conso distrito 01,3209201001 Vilariño de Conso sección 01001,Mujeres,Extranjera,Población con ingresos por unidad de consumo p...,2016,0.0
78731,32092 Vilariño de Conso,3209201 Vilariño de Conso distrito 01,3209201001 Vilariño de Conso sección 01001,Mujeres,Extranjera,Población con ingresos por unidad de consumo p...,2015,0.0

**Veamos los tipos de las columnas y convertimos los object a category (excepto la columna Total)**

In [14]:
for col in data.columns:
    print(f"{col} -> {data[col].dtype}")
    if data[col].dtype == "object" and col != data.Total.name:
        data[col] = data[col].astype("category")

print("\n Visualización del cambio \n")
for col in data.columns:
    print(f"{col} -> {data[col].dtype}")

Municipios -> object
Distritos -> object
Secciones -> object
Sexo -> object
Nacionalidad -> object
Distribución de la renta por unidad de consumo -> object
Periodo -> int64
Total -> float64

 Visualización del cambio

Municipios -> category
Distritos -> category
Secciones -> category
Sexo -> category
Nacionalidad -> category
Distribución de la renta por unidad de consumo -> category
Periodo -> int64
Total -> float64

**Agregamos una nueva columna con los códigos postales**

In [15]:
data["Cod_Postal"] = str(data.Municipios).split()[1]
display(data)

,Municipios,Distritos,Secciones,Sexo,Nacionalidad,Distribución de la renta por unidad de consumo,Periodo,Total,Cod_Postal
0,32001 Allariz,No,No,Total,Española,Población con ingresos por unidad de consumo p...,2023,0.0,32001
1,32001 Allariz,No,No,Total,Española,Población con ingresos por unidad de consumo p...,2022,0.0,32001
2,32001 Allariz,No,No,Total,Española,Población con ingresos por unidad de consumo p...,2021,0.0,32001
3,32001 Allariz,No,No,Total,Española,Población con ingresos por unidad de consumo p...,2020,0.0,32001
4,32001 Allariz,No,No,Total,Española,Población con ingresos por unidad de consumo p...,2019,0.0,32001
...,...,...,...,...,...,...,...,...,...
78727,32092 Vilariño de Conso,3209201 Vilariño de Conso distrito 01,3209201001 Vilariño de Conso sección 01001,Mujeres,Extranjera,Población con ingresos por unidad de consumo p...,2019,0.0,32001
78728,32092 Vilariño de Conso,3209201 Vilariño de Conso distrito 01,3209201001 Vilariño de Conso sección 01001,Mujeres,Extranjera,Población con ingresos por unidad de consumo p...,2018,0.0,32001
78729,32092 Vilariño de Conso,3209201 Vilariño de Conso distrito 01,3209201001 Vilariño de Conso sección 01001,Mujeres,Extranjera,Población con ingresos por unidad de consumo p...,2017,0.0,32001
78730,32092 Vilariño de Conso,3209201 Vilariño de Conso distrito 01,3209201001 Vilariño de Conso sección 01001,Mujeres,Extranjera,Población con ingresos por unidad de consumo p...,2016,0.0,32001
78731,32092 Vilariño de Conso,3209201 Vilariño de Conso distrito 01,3209201001 Vilariño de Conso sección 01001,Mujeres,Extranjera,Población con ingresos por unidad de consumo p...,2015,0.0,32001

**Normalizamos el periodo con datetime y ordenamos por Periodo y Codigo postal**

In [16]:
data.Periodo = pd.to_datetime(data.Periodo, format="%Y")
data = data.sort_values(["Periodo","Cod_Postal"], ascending=[True ,False])
display(data)

,Municipios,Distritos,Secciones,Sexo,Nacionalidad,Distribución de la renta por unidad de consumo,Periodo,Total,Cod_Postal
8,32001 Allariz,No,No,Total,Española,Población con ingresos por unidad de consumo p...,2015-01-01,0.0,32001
17,32001 Allariz,No,No,Total,Española,Población con ingresos por unidad de consumo p...,2015-01-01,0.0,32001
26,32001 Allariz,No,No,Total,Española,Población con ingresos por unidad de consumo p...,2015-01-01,0.0,32001
35,32001 Allariz,No,No,Total,Extranjera,Población con ingresos por unidad de consumo p...,2015-01-01,0.0,32001
44,32001 Allariz,No,No,Total,Extranjera,Población con ingresos por unidad de consumo p...,2015-01-01,0.0,32001
...,...,...,...,...,...,...,...,...,...
78687,32092 Vilariño de Conso,3209201 Vilariño de Conso distrito 01,3209201001 Vilariño de Conso sección 01001,Mujeres,Española,Población con ingresos por unidad de consumo p...,2023-01-01,0.0,32001
78696,32092 Vilariño de Conso,3209201 Vilariño de Conso distrito 01,3209201001 Vilariño de Conso sección 01001,Mujeres,Española,Población con ingresos por unidad de consumo p...,2023-01-01,0.0,32001
78705,32092 Vilariño de Conso,3209201 Vilariño de Conso distrito 01,3209201001 Vilariño de Conso sección 01001,Mujeres,Extranjera,Población con ingresos por unidad de consumo p...,2023-01-01,0.0,32001
78714,32092 Vilariño de Conso,3209201 Vilariño de Conso distrito 01,3209201001 Vilariño de Conso sección 01001,Mujeres,Extranjera,Población con ingresos por unidad de consumo p...,2023-01-01,0.0,32001
78723,32092 Vilariño de Conso,3209201 Vilariño de Conso distrito 01,3209201001 Vilariño de Conso sección 01001,Mujeres,Extranjera,Población con ingresos por unidad de consumo p...,2023-01-01,0.0,32001

**Categorizamos los valores de TOTAL por Bajo, Medio y Alto**

In [17]:
aux = data.Total.drop_duplicates()
print(f"Entendemos que el porcentaje es de 0% a 100% entonces separamos cada 33,3%")

min = 0.0
min_med = 33.33
max_med = 66.66
max = 100.00

data["Porcentaje"] = pd.cut(data.Total, [min, min_med, max_med, max], labels=["Bajo", "Medio", "Alto"], right=False) # rigt=False para que coja el valor 0.0 como dentor del rango Bajo
# data["Porcentaje"] = data.Porcentaje.astype("category")

display(data)

Entendemos que el porcentaje es de 0% a 100% entonces separamos cada 33,3%

,Municipios,Distritos,Secciones,Sexo,Nacionalidad,Distribución de la renta por unidad de consumo,Periodo,Total,Cod_Postal,Porcentaje
8,32001 Allariz,No,No,Total,Española,Población con ingresos por unidad de consumo p...,2015-01-01,0.0,32001,Bajo
17,32001 Allariz,No,No,Total,Española,Población con ingresos por unidad de consumo p...,2015-01-01,0.0,32001,Bajo
26,32001 Allariz,No,No,Total,Española,Población con ingresos por unidad de consumo p...,2015-01-01,0.0,32001,Bajo
35,32001 Allariz,No,No,Total,Extranjera,Población con ingresos por unidad de consumo p...,2015-01-01,0.0,32001,Bajo
44,32001 Allariz,No,No,Total,Extranjera,Población con ingresos por unidad de consumo p...,2015-01-01,0.0,32001,Bajo
...,...,...,...,...,...,...,...,...,...,...
78687,32092 Vilariño de Conso,3209201 Vilariño de Conso distrito 01,3209201001 Vilariño de Conso sección 01001,Mujeres,Española,Población con ingresos por unidad de consumo p...,2023-01-01,0.0,32001,Bajo
78696,32092 Vilariño de Conso,3209201 Vilariño de Conso distrito 01,3209201001 Vilariño de Conso sección 01001,Mujeres,Española,Población con ingresos por unidad de consumo p...,2023-01-01,0.0,32001,Bajo
78705,32092 Vilariño de Conso,3209201 Vilariño de Conso distrito 01,3209201001 Vilariño de Conso sección 01001,Mujeres,Extranjera,Población con ingresos por unidad de consumo p...,2023-01-01,0.0,32001,Bajo
78714,32092 Vilariño de Conso,3209201 Vilariño de Conso distrito 01,3209201001 Vilariño de Conso sección 01001,Mujeres,Extranjera,Población con ingresos por unidad de consumo p...,2023-01-01,0.0,32001,Bajo
78723,32092 Vilariño de Conso,3209201 Vilariño de Conso distrito 01,3209201001 Vilariño de Conso sección 01001,Mujeres,Extranjera,Población con ingresos por unidad de consumo p...,2023-01-01,0.0,32001,Bajo

**Guardamos los datos limpios en un CSV sin índice**

In [18]:
data.to_csv(path_or_buf="./dist_renta_hogares_limpio.csv",index=False)