**Cargamos librerías y datos**

In [18]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as mp

data = pd.read_csv("avistamientos_aerostatos.csv")

**Carga y exploración estructural**

In [32]:
print("HEAD")
display(data.head(10))
print("TAIL")
display(data.tail())

print("\nComprobación de nulos")
print("=======================\n")

for s in data:
    print(data[s].name," - ",pd.isna(s))

print("\n -- NO HAY NULOS --\n")

print("Comprobamos los campos categorizables")
print("=====================================")

for s in data:
    aux = data[s].drop_duplicates()
    aux_n = str(data[s].name)
    aux_rep = []
    
    if aux.__len__() < 20: # Si tiene más de 20 tipos no lo tomamos como categorizable
        for i in aux:
            rep = [data[s] == i].count("True")
            aux_rep.append(i,rep)        
        
        
        print(data[s].name)
        print("-"*aux_n.__len__())
        display(aux)




# print("Tipos de datos")
# print("==============")
# print(data.dtypes)

# print("\n optimicemos memoria convirtiendo los tipo object en distintos tipos primarios o categorizando\n")




# print("Tipos de datos optimizados")
# print("==========================")
# print(data.dtypes)

# print("\n-> Vemos que en la columna Pais_Origen hay un celdas rellenas como Desconocido, hay que vigilar esa columna.")
# print("-> Además hay bastantes registros repetidos, todos los de la cola están también en el inicio del fichero.")

HEAD

,ID_Registro,Pais_Origen,Altitud_km,Duracion_Vuelo_h,Velocidad_Viento_kmh,Tecnologia_Detectada,Cercania_Base_Militar_km,Fecha_Avistamiento,Indice_Maniobra
0,REG-1000,EE.UU.,150.00,76.1,82.6,Vigilancia Radar,35.40,2023-02-07,49.38
1,REG-1001,Desconocido,0.50,10.4,94.1,Inteligencia de Señales,103.66,2023-01-31,21.20
2,REG-1002,EE.UU.,25.24,5000.0,39.2,Vigilancia Radar,34.02,2023-01-31,63.00
3,REG-1003,China,29.62,23.0,12.3,Meteorológico,60.58,2023-01-02,96.11
4,REG-1004,Rusia,20.83,26.7,19.0,Meteorológico,246.80,2023-02-06,101.54
5,REG-1005,EE.UU.,20.83,41.5,116.5,Inteligencia de Señales,7.05,2023-01-17,22.01
6,REG-1006,EE.UU.,29.90,19.4,42.5,Vigilancia Radar,16.06,2023-01-08,67.12
7,REG-1007,China,25.84,33.0,94.6,Vigilancia Radar,25.09,2023-01-09,33.77
8,REG-1008,Rusia,19.65,18.0,78.7,Inteligencia de Señales,27.39,2023-02-27,32.41
9,REG-1009,China,24.71,24.7,52.0,Meteorológico,26.47,2023-01-29,69.65

TAIL

,ID_Registro,Pais_Origen,Altitud_km,Duracion_Vuelo_h,Velocidad_Viento_kmh,Tecnologia_Detectada,Cercania_Base_Militar_km,Fecha_Avistamiento,Indice_Maniobra
505,REG-1005,EE.UU.,20.83,41.5,116.5,Inteligencia de Señales,7.05,2023-01-17,22.01
506,REG-1006,EE.UU.,29.90,19.4,42.5,Vigilancia Radar,16.06,2023-01-08,67.12
507,REG-1007,China,25.84,33.0,94.6,Vigilancia Radar,25.09,2023-01-09,33.77
508,REG-1008,Rusia,19.65,18.0,78.7,Inteligencia de Señales,27.39,2023-02-27,32.41
509,REG-1009,China,24.71,24.7,52.0,Meteorológico,26.47,2023-01-29,69.65

Comprobación de nulos
=======================

ID_Registro  -  False
Pais_Origen  -  False
Altitud_km  -  False
Duracion_Vuelo_h  -  False
Velocidad_Viento_kmh  -  False
Tecnologia_Detectada  -  False
Cercania_Base_Militar_km  -  False
Fecha_Avistamiento  -  False
Indice_Maniobra  -  False

 -- NO HAY NULOS --

Comprobamos los campos categorizables
=====================================

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().