**Importación de librerías**

In [1]:
import os
import numpy as np
import matplotlib as mp
import matplotlib.pyplot as plt
import pandas as pd

**PRÁCTICA 2**  
*1. Introduce manualmente valores nulos en las columnas:*  
• city  
• min_experience_years  

Quitados (fila-valor):  
- City: 7-Seattle, 49997-Melbourne, 26462-London  
- min_experience_years: 34-2, 32341-0, 39861-5

*2. Crea al menos dos duplicados reales duplicando filas completas del DataFrame.*
- Copio: 142 -> 143, 174444 -> 31183, 23916 -> 42138

**1. Importación y Exploración Estructural (RA2.a)**  
  
• Importa la librería Pandas y carga el archivo usando read_csv, especificando que el delimitador es una coma.  
• Muestra las primeras 10 filas con el método .head(10) para comprender la disposición de las columnas y los tipos de datos presentes.  
• Utiliza el atributo .size y .index para conocer el volumen total de registros y etiquetas del eje.

In [2]:
fic_csv_nom = "ai_jobs.csv" # El csv se encontrará en el mismo fichero que el ipynb
path_csv = os.path.join(os.getcwd(),fic_csv_nom) # En los ficheros ipynb no funciona __file__ porque no es un script estandar de python

data = pd.read_csv(fic_csv_nom,delimiter=",")
data_head = list(data.axes[1]) # Guardamos las cabeceras del dataframe en un array

# print(data_head)
display(data.head(10))

print("Nº Registros: ",data.job_id.size, " -- Nº de datos:",data.size)

,job_id,job_title,company_type,industry,country,city,remote_type,experience_level,min_experience_years,salary_min_usd,salary_max_usd,employment_type,posted_year,company_size
0,0IFD0TVBDIVU,MLOps Engineer,Research Lab,Education,Australia,Remote,Remote,Entry,0.0,56873,72223,Full-time,2023,Large
1,ZMF8MDD4V30T,Data Analyst,Startup,Education,Germany,Remote,Remote,Entry,0.0,54803,85599,Full-time,2024,Medium
2,CX1945NQ4FMY,MLOps Engineer,Research Lab,Tech,Canada,Remote,Remote,Senior,5.0,149980,175806,Full-time,2021,Large
3,QJ7YHL1C32OC,Applied Scientist,Research Lab,Healthcare,Australia,Remote,Remote,Entry,0.0,53483,86477,Full-time,2023,Medium
4,F0T0PVN9ER14,Machine Learning Engineer,Research Lab,Finance,Australia,Sydney,Hybrid,Mid,2.0,102977,127298,Full-time,2023,Large
5,9T84AZYTJXEP,Data Analyst,Startup,Healthcare,USA,NaN,Hybrid,Senior,5.0,148201,179967,Full-time,2021,Large
6,SHNF877VREN9,AI Researcher,Startup,Tech,USA,Austin,Onsite,Senior,5.0,143946,173591,Full-time,2020,Small
7,1ERTJ5PHT0HL,MLOps Engineer,Research Lab,Healthcare,Australia,Sydney,Hybrid,Senior,5.0,147177,171959,Full-time,2023,Small
8,MVIHCWI64CIY,Machine Learning Engineer,Research Lab,Finance,India,Remote,Remote,Entry,0.0,61851,83711,Full-time,2024,Medium
9,DXMO5BXXC02D,Machine Learning Engineer,Startup,Education,India,Chennai,Hybrid,Entry,0.0,57350,69593,Full-time,2023,Small

Nº Registros:  50000  -- Nº de datos: 700000

**2. Diagnóstico de Calidad y Gestión de Nulos (RA2.b, RA2.c)**  
  
• Detecta la presencia de valores ausentes (NaN) en todo el DataFrame mediante las funciones isna() o notna().  
• Tratamiento de nulos en "ciudad": Dado que los trabajos remotos pueden no tener ciudad, rellena los valores faltantes en esta columna  con la etiqueta "Sin especificar/Remoto" usando un valor escalar en fillna().  
• Tratamiento de nulos en "min_años_de_experiencia": Sustituye los valores nulos por la mediana de los años de experiencia para evitar  distorsiones en cálculos matemáticos posteriores.

In [3]:
display(data.head(10))
print("¿Tiene nulos? ->", np.where(np.any(data.isna()), "Si", "No")) # Indicamos si tiene o no nulos con isna()
print("¿Tiene nulos? ->", np.where(np.all(data.notna()), "No", "Si")) # Indicamos si tiene o no nulos con isna()

print("\nColumnas con nulos:\n")
for col in data:
    print("Col.", col, " -> ", np.where(np.any(data[col].isna()),"Si","No"))

print("\n=====================================\n")
print("Sustitución de NaN por Remote\n")
data.city = data.city.fillna("Remote")
data.min_experience_years = data.min_experience_years.fillna(data.min_experience_years.mean())
display(data.head(10))

print("¿Tiene nulos? ->", np.where(np.any(data.isna()), "Si", "No")) # Indicamos si tiene o no nulos con isna()
print("¿Tiene nulos? ->", np.where(np.all(data.notna()), "No", "Si")) # Indicamos si tiene o no nulos con isna()

print("\nColumnas con nulos:\n")
for col in data:
    print("Col.", col, " -> ", np.where(np.any(data[col].isna()),"Si","No"))

,job_id,job_title,company_type,industry,country,city,remote_type,experience_level,min_experience_years,salary_min_usd,salary_max_usd,employment_type,posted_year,company_size
0,0IFD0TVBDIVU,MLOps Engineer,Research Lab,Education,Australia,Remote,Remote,Entry,0.0,56873,72223,Full-time,2023,Large
1,ZMF8MDD4V30T,Data Analyst,Startup,Education,Germany,Remote,Remote,Entry,0.0,54803,85599,Full-time,2024,Medium
2,CX1945NQ4FMY,MLOps Engineer,Research Lab,Tech,Canada,Remote,Remote,Senior,5.0,149980,175806,Full-time,2021,Large
3,QJ7YHL1C32OC,Applied Scientist,Research Lab,Healthcare,Australia,Remote,Remote,Entry,0.0,53483,86477,Full-time,2023,Medium
4,F0T0PVN9ER14,Machine Learning Engineer,Research Lab,Finance,Australia,Sydney,Hybrid,Mid,2.0,102977,127298,Full-time,2023,Large
5,9T84AZYTJXEP,Data Analyst,Startup,Healthcare,USA,NaN,Hybrid,Senior,5.0,148201,179967,Full-time,2021,Large
6,SHNF877VREN9,AI Researcher,Startup,Tech,USA,Austin,Onsite,Senior,5.0,143946,173591,Full-time,2020,Small
7,1ERTJ5PHT0HL,MLOps Engineer,Research Lab,Healthcare,Australia,Sydney,Hybrid,Senior,5.0,147177,171959,Full-time,2023,Small
8,MVIHCWI64CIY,Machine Learning Engineer,Research Lab,Finance,India,Remote,Remote,Entry,0.0,61851,83711,Full-time,2024,Medium
9,DXMO5BXXC02D,Machine Learning Engineer,Startup,Education,India,Chennai,Hybrid,Entry,0.0,57350,69593,Full-time,2023,Small

¿Tiene nulos? -> Si
¿Tiene nulos? -> Si

Columnas con nulos:

Col. job_id  ->  No
Col. job_title  ->  No
Col. company_type  ->  No
Col. industry  ->  No
Col. country  ->  No
Col. city  ->  Si
Col. remote_type  ->  No
Col. experience_level  ->  No
Col. min_experience_years  ->  Si
Col. salary_min_usd  ->  No
Col. salary_max_usd  ->  No
Col. employment_type  ->  No
Col. posted_year  ->  No
Col. company_size  ->  No

=====================================

Sustitución de NaN por Remote

,job_id,job_title,company_type,industry,country,city,remote_type,experience_level,min_experience_years,salary_min_usd,salary_max_usd,employment_type,posted_year,company_size
0,0IFD0TVBDIVU,MLOps Engineer,Research Lab,Education,Australia,Remote,Remote,Entry,0.0,56873,72223,Full-time,2023,Large
1,ZMF8MDD4V30T,Data Analyst,Startup,Education,Germany,Remote,Remote,Entry,0.0,54803,85599,Full-time,2024,Medium
2,CX1945NQ4FMY,MLOps Engineer,Research Lab,Tech,Canada,Remote,Remote,Senior,5.0,149980,175806,Full-time,2021,Large
3,QJ7YHL1C32OC,Applied Scientist,Research Lab,Healthcare,Australia,Remote,Remote,Entry,0.0,53483,86477,Full-time,2023,Medium
4,F0T0PVN9ER14,Machine Learning Engineer,Research Lab,Finance,Australia,Sydney,Hybrid,Mid,2.0,102977,127298,Full-time,2023,Large
5,9T84AZYTJXEP,Data Analyst,Startup,Healthcare,USA,Remote,Hybrid,Senior,5.0,148201,179967,Full-time,2021,Large
6,SHNF877VREN9,AI Researcher,Startup,Tech,USA,Austin,Onsite,Senior,5.0,143946,173591,Full-time,2020,Small
7,1ERTJ5PHT0HL,MLOps Engineer,Research Lab,Healthcare,Australia,Sydney,Hybrid,Senior,5.0,147177,171959,Full-time,2023,Small
8,MVIHCWI64CIY,Machine Learning Engineer,Research Lab,Finance,India,Remote,Remote,Entry,0.0,61851,83711,Full-time,2024,Medium
9,DXMO5BXXC02D,Machine Learning Engineer,Startup,Education,India,Chennai,Hybrid,Entry,0.0,57350,69593,Full-time,2023,Small

¿Tiene nulos? -> No
¿Tiene nulos? -> No

Columnas con nulos:

Col. job_id  ->  No
Col. job_title  ->  No
Col. company_type  ->  No
Col. industry  ->  No
Col. country  ->  No
Col. city  ->  No
Col. remote_type  ->  No
Col. experience_level  ->  No
Col. min_experience_years  ->  No
Col. salary_min_usd  ->  No
Col. salary_max_usd  ->  No
Col. employment_type  ->  No
Col. posted_year  ->  No
Col. company_size  ->  No

**3. Limpieza de Redundancias e Integridad (RA2.c)**  
• Verifica si existen ofertas de empleo duplicadas basándote en la columna id_del_trabajo
usando duplicated().  
• Elimina los registros duplicados de forma permanente con el método drop_duplicates().  
• Identifica columnas que no aporten valor al análisis estadístico (como id_del_trabajo si ya no
es necesario) y elimínala usando el comando del.

In [4]:
print("¿Tiene duplicados? ",np.any(data.job_id.duplicated()))

# Visualización de los job_id duplicados
# filas_duplicadas = data.job_id[data.job_id.duplicated(keep=False)]
# print(f"Número de filas duplicadas: {len(filas_duplicadas)}")
# print(filas_duplicadas)

data = data.drop_duplicates(subset=["job_id"])
print("¿Tiene duplicados ahora? ",np.any(data.job_id.duplicated()))

del data["job_id"]
display(data)

¿Tiene duplicados?  True
¿Tiene duplicados ahora?  False

,job_title,company_type,industry,country,city,remote_type,experience_level,min_experience_years,salary_min_usd,salary_max_usd,employment_type,posted_year,company_size
0,MLOps Engineer,Research Lab,Education,Australia,Remote,Remote,Entry,0.0,56873,72223,Full-time,2023,Large
1,Data Analyst,Startup,Education,Germany,Remote,Remote,Entry,0.0,54803,85599,Full-time,2024,Medium
2,MLOps Engineer,Research Lab,Tech,Canada,Remote,Remote,Senior,5.0,149980,175806,Full-time,2021,Large
3,Applied Scientist,Research Lab,Healthcare,Australia,Remote,Remote,Entry,0.0,53483,86477,Full-time,2023,Medium
4,Machine Learning Engineer,Research Lab,Finance,Australia,Sydney,Hybrid,Mid,2.0,102977,127298,Full-time,2023,Large
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,AI Researcher,MNC,Retail,Australia,Remote,Onsite,Senior,5.0,143800,174698,Full-time,2023,Medium
49996,Data Scientist,Startup,Retail,Canada,Vancouver,Onsite,Senior,5.0,140248,161993,Full-time,2024,Medium
49997,Data Analyst,Startup,Healthcare,USA,New York,Onsite,Entry,0.0,50953,87158,Full-time,2022,Small
49998,Data Scientist,Research Lab,Healthcare,USA,Austin,Hybrid,Entry,0.0,63712,76213,Full-time,2020,Large
49999,Applied Scientist,MNC,Retail,Canada,Montreal,Hybrid,Senior,5.0,148500,166972,Full-time,2021,Small

**4. Transformación y Conversión de Datos (RA2.e, RA2.f)**  
• Normalización de Fechas: Convierte la columna año_publicado al tipo de dato datetime de Pandas usando pd.to_datetime() para facilitar  futuros análisis temporales.  
• Cálculo de Variables Cuantitativas: Crea una nueva columna llamada salario_promedio_usd que sea el resultado de la media aritmética  entre salario_mínimo_usd y salario_máximo_usd.  
• Conversión de Categóricos: Identifica las columnas de tipo object (como tamaño de la empresa) y conviértelas al tipo de dato category  para optimizar el rendimiento y la memoria.

In [5]:
data["posted_year"] = pd.to_datetime(data["posted_year"],format="%Y")

# data["salario_promedio_usd"] = pd.Series((data.salary_max_usd + data.salary_min_usd)/2) -> funciona pero no me gusta
data["salario_promedio_usd"] = data[["salary_min_usd","salary_max_usd"]].mean(axis=1) # axis=1 significa en eje horizontal - axis=0 es el eje vertical

#display(data)

# Primero hacemos un estudio de las columnas tipo object para ver si tiene sentido transformarlos a tipo category
for l in data.columns:
    aux = pd.Series
    if data[l].dtype == "object":
        aux = data[l].drop_duplicates()
        print(l," - ",data[l].dtype, " -> ", aux.__len__())
    # else:
    #     print(l," - ",data[l].dtype)
    
# Como no hay ningún campo object con muchos valores únicos tiene sentido transformarlos todos a category

for l in data.columns:
    if data[l].dtype == "object":
        data[l] = data[l].astype("category")

print("\n\n")
for l in data.columns:
    print(l," - ",data[l].dtype)

job_title  -  object  ->  6
company_type  -  object  ->  3
industry  -  object  ->  5
country  -  object  ->  6
city  -  object  ->  24
remote_type  -  object  ->  3
experience_level  -  object  ->  3
employment_type  -  object  ->  1
company_size  -  object  ->  3



job_title  -  category
company_type  -  category
industry  -  category
country  -  category
city  -  category
remote_type  -  category
experience_level  -  category
min_experience_years  -  float64
salary_min_usd  -  int64
salary_max_usd  -  int64
employment_type  -  category
posted_year  -  datetime64[ns]
company_size  -  category
salario_promedio_usd  -  float64

**5. Agrupación por Intervalos (Binning) (RA2.d)**  
• Utiliza la función pd.cut() para crear una nueva columna llamada rango_salarial. Divide los salarios en tres categorías: "Entrada", "Competitivo" y "Top", definiendo  manualmente los límites de los intervalos basándote en la columna salario_máximo_usd.

In [6]:
aux = data.salary_max_usd.drop_duplicates() # serie para estudiar los valores de la columna de salarios máximos
max = aux.max()
min = aux.min()
med = int(aux.mean().__round__())
min_med = int((min + med)/2).__round__() # Para el rango "competitivo" hacemos la media entre salrio mínimo y la media de maximo y mínimo
max_med = int((max + med)/2).__round__() # y la media entre salrio máximo y la media de maximo y mínimo

print("Min: ",min)
print("Min med:",min_med)
print("Med: ",med)
print("Max med:",max_med)
print("Max: ",max)

print("\n","="*10,"\n")

data["rango_salarial"] = pd.cut(data.salary_max_usd,[min, min_med, max_med, max],labels=["Entrada", "Competitivo", "Top"])

display(data)

Min:  65000
Min med: 92941
Med:  120883
Max med: 150441
Max:  180000

 ==========

,job_title,company_type,industry,country,city,remote_type,experience_level,min_experience_years,salary_min_usd,salary_max_usd,employment_type,posted_year,company_size,salario_promedio_usd,rango_salarial
0,MLOps Engineer,Research Lab,Education,Australia,Remote,Remote,Entry,0.0,56873,72223,Full-time,2023-01-01,Large,64548.0,Entrada
1,Data Analyst,Startup,Education,Germany,Remote,Remote,Entry,0.0,54803,85599,Full-time,2024-01-01,Medium,70201.0,Entrada
2,MLOps Engineer,Research Lab,Tech,Canada,Remote,Remote,Senior,5.0,149980,175806,Full-time,2021-01-01,Large,162893.0,Top
3,Applied Scientist,Research Lab,Healthcare,Australia,Remote,Remote,Entry,0.0,53483,86477,Full-time,2023-01-01,Medium,69980.0,Entrada
4,Machine Learning Engineer,Research Lab,Finance,Australia,Sydney,Hybrid,Mid,2.0,102977,127298,Full-time,2023-01-01,Large,115137.5,Competitivo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,AI Researcher,MNC,Retail,Australia,Remote,Onsite,Senior,5.0,143800,174698,Full-time,2023-01-01,Medium,159249.0,Top
49996,Data Scientist,Startup,Retail,Canada,Vancouver,Onsite,Senior,5.0,140248,161993,Full-time,2024-01-01,Medium,151120.5,Top
49997,Data Analyst,Startup,Healthcare,USA,New York,Onsite,Entry,0.0,50953,87158,Full-time,2022-01-01,Small,69055.5,Entrada
49998,Data Scientist,Research Lab,Healthcare,USA,Austin,Hybrid,Entry,0.0,63712,76213,Full-time,2020-01-01,Large,69962.5,Entrada
49999,Applied Scientist,MNC,Retail,Canada,Montreal,Hybrid,Senior,5.0,148500,166972,Full-time,2021-01-01,Small,157736.0,Top

**6. Ordenación y Exportación Final**  
• Ordena el DataFrame final de forma descendente por año_publicado y, en caso de empate, por salario_máximo_usd usando sort_values().  
• Exporta el lote de datos limpio y estandarizado a un archivo llamado ai_jobs_clean.csv empleando el método to_csv, asegurándote de no incluir el índice automático en el  archivo final.

In [7]:
data_sorted = data.sort_values(["posted_year","salary_max_usd"], ascending=[True ,False])
display(data)

data_sorted.to_csv(path_or_buf="./ai_jobs_clean.csv",index=False)

,job_title,company_type,industry,country,city,remote_type,experience_level,min_experience_years,salary_min_usd,salary_max_usd,employment_type,posted_year,company_size,salario_promedio_usd,rango_salarial
0,MLOps Engineer,Research Lab,Education,Australia,Remote,Remote,Entry,0.0,56873,72223,Full-time,2023-01-01,Large,64548.0,Entrada
1,Data Analyst,Startup,Education,Germany,Remote,Remote,Entry,0.0,54803,85599,Full-time,2024-01-01,Medium,70201.0,Entrada
2,MLOps Engineer,Research Lab,Tech,Canada,Remote,Remote,Senior,5.0,149980,175806,Full-time,2021-01-01,Large,162893.0,Top
3,Applied Scientist,Research Lab,Healthcare,Australia,Remote,Remote,Entry,0.0,53483,86477,Full-time,2023-01-01,Medium,69980.0,Entrada
4,Machine Learning Engineer,Research Lab,Finance,Australia,Sydney,Hybrid,Mid,2.0,102977,127298,Full-time,2023-01-01,Large,115137.5,Competitivo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,AI Researcher,MNC,Retail,Australia,Remote,Onsite,Senior,5.0,143800,174698,Full-time,2023-01-01,Medium,159249.0,Top
49996,Data Scientist,Startup,Retail,Canada,Vancouver,Onsite,Senior,5.0,140248,161993,Full-time,2024-01-01,Medium,151120.5,Top
49997,Data Analyst,Startup,Healthcare,USA,New York,Onsite,Entry,0.0,50953,87158,Full-time,2022-01-01,Small,69055.5,Entrada
49998,Data Scientist,Research Lab,Healthcare,USA,Austin,Hybrid,Entry,0.0,63712,76213,Full-time,2020-01-01,Large,69962.5,Entrada
49999,Applied Scientist,MNC,Retail,Canada,Montreal,Hybrid,Senior,5.0,148500,166972,Full-time,2021-01-01,Small,157736.0,Top