**Importación de librerías**

In [1]:
import os
import csv
import numpy as np
import matplotlib as mp
import matplotlib.pyplot as plt
import pandas as pd

**PRÁCTICA 2**  
*1. Introduce manualmente valores nulos en las columnas:*  
• city  
• min_experience_years  

Quitados (fila-valor):  
- City: 7-Seattle, 49997-Melbourne, 26462-London  
- min_experience_years: 34-2, 32341-0, 39861-5

*2. Crea al menos dos duplicados reales duplicando filas completas del DataFrame.*
- Copio: 142 -> 143, 174444 -> 31183, 23916 -> 42138

**1. Importación y Exploración Estructural (RA2.a)**  
  
• Importa la librería Pandas y carga el archivo usando read_csv, especificando que el delimitador es una coma.  
• Muestra las primeras 10 filas con el método .head(10) para comprender la disposición de las columnas y los tipos de datos presentes.  
• Utiliza el atributo .size y .index para conocer el volumen total de registros y etiquetas del eje.

In [2]:
fic_csv_nom = "ai_jobs.csv" # El csv se encontrará en el mismo fichero que el ipynb
path_csv = os.path.join(os.getcwd(),fic_csv_nom) # En los ficheros ipynb no funciona __file__ porque no es un script estandar de python

data = pd.read_csv(fic_csv_nom,delimiter=",")
data_head = list(data.axes[1]) # Guardamos las cabeceras del dataframe en un array

# print(data_head)
display(data.head(10))

print("Nº Registros: ",data.job_id.size, " -- Nº de datos:",data.size)

,job_id,job_title,company_type,industry,country,city,remote_type,experience_level,min_experience_years,salary_min_usd,salary_max_usd,employment_type,posted_year,company_size
0,0IFD0TVBDIVU,MLOps Engineer,Research Lab,Education,Australia,Remote,Remote,Entry,0.0,56873,72223,Full-time,2023,Large
1,ZMF8MDD4V30T,Data Analyst,Startup,Education,Germany,Remote,Remote,Entry,0.0,54803,85599,Full-time,2024,Medium
2,CX1945NQ4FMY,MLOps Engineer,Research Lab,Tech,Canada,Remote,Remote,Senior,5.0,149980,175806,Full-time,2021,Large
3,QJ7YHL1C32OC,Applied Scientist,Research Lab,Healthcare,Australia,Remote,Remote,Entry,0.0,53483,86477,Full-time,2023,Medium
4,F0T0PVN9ER14,Machine Learning Engineer,Research Lab,Finance,Australia,Sydney,Hybrid,Mid,2.0,102977,127298,Full-time,2023,Large
5,9T84AZYTJXEP,Data Analyst,Startup,Healthcare,USA,NaN,Hybrid,Senior,5.0,148201,179967,Full-time,2021,Large
6,SHNF877VREN9,AI Researcher,Startup,Tech,USA,Austin,Onsite,Senior,5.0,143946,173591,Full-time,2020,Small
7,1ERTJ5PHT0HL,MLOps Engineer,Research Lab,Healthcare,Australia,Sydney,Hybrid,Senior,5.0,147177,171959,Full-time,2023,Small
8,MVIHCWI64CIY,Machine Learning Engineer,Research Lab,Finance,India,Remote,Remote,Entry,0.0,61851,83711,Full-time,2024,Medium
9,DXMO5BXXC02D,Machine Learning Engineer,Startup,Education,India,Chennai,Hybrid,Entry,0.0,57350,69593,Full-time,2023,Small

Nº Registros:  50000  -- Nº de datos: 700000

**2. Diagnóstico de Calidad y Gestión de Nulos (RA2.b, RA2.c)**  
  
• Detecta la presencia de valores ausentes (NaN) en todo el DataFrame mediante las funciones isna() o notna().  
• Tratamiento de nulos en "ciudad": Dado que los trabajos remotos pueden no tener ciudad, rellena los valores faltantes en esta columna  con la etiqueta "Sin especificar/Remoto" usando un valor escalar en fillna().  
• Tratamiento de nulos en "min_años_de_experiencia": Sustituye los valores nulos por la mediana de los años de experiencia para evitar  distorsiones en cálculos matemáticos posteriores.

In [3]:
display(data.head(10))
print("¿Tiene nulos? ->", np.where(np.any(data.isna()), "Si", "No")) # Indicamos si tiene o no nulos con isna()
print("¿Tiene nulos? ->", np.where(np.all(data.notna()), "No", "Si")) # Indicamos si tiene o no nulos con isna()

print("\nColumnas con nulos:\n")
for col in data:
    print("Col.", col, " -> ", np.where(np.any(data[col].isna()),"Si","No"))

print("\n=====================================\n")
print("Sustitución de NaN por Remote\n")
data.city = data.city.fillna("Remote")
data.min_experience_years = data.min_experience_years.fillna(data.min_experience_years.mean())
display(data.head(10))

print("¿Tiene nulos? ->", np.where(np.any(data.isna()), "Si", "No")) # Indicamos si tiene o no nulos con isna()
print("¿Tiene nulos? ->", np.where(np.all(data.notna()), "No", "Si")) # Indicamos si tiene o no nulos con isna()

print("\nColumnas con nulos:\n")
for col in data:
    print("Col.", col, " -> ", np.where(np.any(data[col].isna()),"Si","No"))

,job_id,job_title,company_type,industry,country,city,remote_type,experience_level,min_experience_years,salary_min_usd,salary_max_usd,employment_type,posted_year,company_size
0,0IFD0TVBDIVU,MLOps Engineer,Research Lab,Education,Australia,Remote,Remote,Entry,0.0,56873,72223,Full-time,2023,Large
1,ZMF8MDD4V30T,Data Analyst,Startup,Education,Germany,Remote,Remote,Entry,0.0,54803,85599,Full-time,2024,Medium
2,CX1945NQ4FMY,MLOps Engineer,Research Lab,Tech,Canada,Remote,Remote,Senior,5.0,149980,175806,Full-time,2021,Large
3,QJ7YHL1C32OC,Applied Scientist,Research Lab,Healthcare,Australia,Remote,Remote,Entry,0.0,53483,86477,Full-time,2023,Medium
4,F0T0PVN9ER14,Machine Learning Engineer,Research Lab,Finance,Australia,Sydney,Hybrid,Mid,2.0,102977,127298,Full-time,2023,Large
5,9T84AZYTJXEP,Data Analyst,Startup,Healthcare,USA,NaN,Hybrid,Senior,5.0,148201,179967,Full-time,2021,Large
6,SHNF877VREN9,AI Researcher,Startup,Tech,USA,Austin,Onsite,Senior,5.0,143946,173591,Full-time,2020,Small
7,1ERTJ5PHT0HL,MLOps Engineer,Research Lab,Healthcare,Australia,Sydney,Hybrid,Senior,5.0,147177,171959,Full-time,2023,Small
8,MVIHCWI64CIY,Machine Learning Engineer,Research Lab,Finance,India,Remote,Remote,Entry,0.0,61851,83711,Full-time,2024,Medium
9,DXMO5BXXC02D,Machine Learning Engineer,Startup,Education,India,Chennai,Hybrid,Entry,0.0,57350,69593,Full-time,2023,Small

¿Tiene nulos? -> Si
¿Tiene nulos? -> Si

Columnas con nulos:

Col. job_id  ->  No
Col. job_title  ->  No
Col. company_type  ->  No
Col. industry  ->  No
Col. country  ->  No
Col. city  ->  Si
Col. remote_type  ->  No
Col. experience_level  ->  No
Col. min_experience_years  ->  Si
Col. salary_min_usd  ->  No
Col. salary_max_usd  ->  No
Col. employment_type  ->  No
Col. posted_year  ->  No
Col. company_size  ->  No

=====================================

Sustitución de NaN por Remote

,job_id,job_title,company_type,industry,country,city,remote_type,experience_level,min_experience_years,salary_min_usd,salary_max_usd,employment_type,posted_year,company_size
0,0IFD0TVBDIVU,MLOps Engineer,Research Lab,Education,Australia,Remote,Remote,Entry,0.0,56873,72223,Full-time,2023,Large
1,ZMF8MDD4V30T,Data Analyst,Startup,Education,Germany,Remote,Remote,Entry,0.0,54803,85599,Full-time,2024,Medium
2,CX1945NQ4FMY,MLOps Engineer,Research Lab,Tech,Canada,Remote,Remote,Senior,5.0,149980,175806,Full-time,2021,Large
3,QJ7YHL1C32OC,Applied Scientist,Research Lab,Healthcare,Australia,Remote,Remote,Entry,0.0,53483,86477,Full-time,2023,Medium
4,F0T0PVN9ER14,Machine Learning Engineer,Research Lab,Finance,Australia,Sydney,Hybrid,Mid,2.0,102977,127298,Full-time,2023,Large
5,9T84AZYTJXEP,Data Analyst,Startup,Healthcare,USA,Remote,Hybrid,Senior,5.0,148201,179967,Full-time,2021,Large
6,SHNF877VREN9,AI Researcher,Startup,Tech,USA,Austin,Onsite,Senior,5.0,143946,173591,Full-time,2020,Small
7,1ERTJ5PHT0HL,MLOps Engineer,Research Lab,Healthcare,Australia,Sydney,Hybrid,Senior,5.0,147177,171959,Full-time,2023,Small
8,MVIHCWI64CIY,Machine Learning Engineer,Research Lab,Finance,India,Remote,Remote,Entry,0.0,61851,83711,Full-time,2024,Medium
9,DXMO5BXXC02D,Machine Learning Engineer,Startup,Education,India,Chennai,Hybrid,Entry,0.0,57350,69593,Full-time,2023,Small

¿Tiene nulos? -> No
¿Tiene nulos? -> No

Columnas con nulos:

Col. job_id  ->  No
Col. job_title  ->  No
Col. company_type  ->  No
Col. industry  ->  No
Col. country  ->  No
Col. city  ->  No
Col. remote_type  ->  No
Col. experience_level  ->  No
Col. min_experience_years  ->  No
Col. salary_min_usd  ->  No
Col. salary_max_usd  ->  No
Col. employment_type  ->  No
Col. posted_year  ->  No
Col. company_size  ->  No

**3. Limpieza de Redundancias e Integridad (RA2.c)**  
• Verifica si existen ofertas de empleo duplicadas basándote en la columna id_del_trabajo
usando duplicated().  
• Elimina los registros duplicados de forma permanente con el método drop_duplicates().  
• Identifica columnas que no aporten valor al análisis estadístico (como id_del_trabajo si ya no
es necesario) y elimínala usando el comando del.