**Carga de CSVs de datos meteorológicos**
El dataset que he elegido es muy grande y está dividido en múltiples .csv, por lo que tengo que hacer un algoritmo que recorra todos los ficheros dentro de la carpeta  
donde tiene

In [52]:
import os
import pandas as pd
import numpy as np
import matplotlib as mp
import matplotlib.pyplot as plt


path = os.path.join(os.getcwd(),"datos/Datos_meteorológicos_por_hora_por_municipio_España/Montly-wheather-data-2015-2020")
lFicheros = os.listdir(path) # listamos todos los csv que hay en la carpeta

print(path)
lFicheros.sort() # ordenamos la lista de ficheros csv a cargar para cargarlos de antiguos a actuales

df1 = pd.Series()

for f in lFicheros:
    print(f)
    df1 = pd.read_csv(os.path.join(path,f),delimiter=";")
    break # descomentar cuando acabemos las pruebas

print(f"Número de registros en s1: {df1["id"].count()}")

for c in df1.axes[1].array:
    print(c, end=" - ")

/home/pepone/Documentos/python/python_curso/Analisis/Bloque 3/Practica_2026_02_04/datos/Datos_meteorológicos_por_hora_por_municipio_España/Montly-wheather-data-2015-2020
datos_2015_1.csv
Número de registros en s1: 2584890
fecha - G(i) - H_sun - T2m - WS10m - id -

**Leyenda de columnas**  
__fecha__ -> fecha de la recogida de los datos  
**G(i)** -> Irradiancia Global en el plano inclinado. Radiación solar por unidad de área (W/m²) que incide sobre una superficie  
**H_sun** -> Horas de Sol durante la cual la radiación solar directa supera un umbral de intensidad  
**T2m** -> Es la Temperatura del Aire a 2 metros. Medida a 2 metros sobre el suelo para evitar la influencia directa de la radiación terrestre  
**WS10m** -> Velocidad del Viento a 10 metros. Es la altura estándar para la medición de la velocidad del viento en meteorología.
**id** -> Id del municipio, que está especificado en el fichero fronteras_municipios.csv

**1.1 Limpieza de datos**  
- Comprabamos si hay nulos
- Comprobamos valores duplicados
- Comprobamos valores incoherentes

In [ ]:
display(df1.head(3))
# Comprobamos si hay valores nulos y si los hay, cuántos.
for i in df1:
    print(f"Columna \"{i}\" tiene nulos: {np.where(np.any(df1[i].isna()), "Si", "No")} - Nº: {df1[i].isna().sum()}")

print(f"\nTipos de las columnas:\n{ df1.dtypes }")
print("\nLa columna 'fecha' es tipo object. Para manejarla la pasaremos a datetime\n")
df1.fecha = pd.to_datetime(df1.fecha)
print(f"\nTipos de las columnas:\n{ df1.dtypes }")
display(df1.head(3))

# Comprobamos si hay valores duplicados
print(f"\nTiene duplicados: {np.where(np.any(df1.duplicated()), "Si", "No")}\n")

# Comprobamos las máximas y mínimas temperaturas para ver si hay alguna medición incoherente
print(f"ºC max: {df1.T2m.max()} - ºC min: {df1.T2m.min()} -> No hay ningúna medida que pueda indicar una mala toma\n")



print(f"Fecha max: {df1.fecha.max()} - Fecha min: {df1.fecha.min()} -> No hay ningúna fecha que pueda indicar una mala toma\n")

# Veamos los datos estadísticos
s_std = df1.T2m.describe() # Como hay valores muy grandes, recorremos el dataframe que devuelve el método para redondear los resultados.
# print(s_std)
for i,j in df1.T2m.describe().items():
    print(f"{i}: {round(j,2)}")

                       fecha   G(i)  H_sun   T2m  WS10m    id
0  2015-01-01 09:09:00+01:00  95.01   6.78  2.07   0.28  4001
1  2015-01-01 09:09:00+01:00  93.01   6.76  1.24   0.07  4002
2  2015-01-01 09:09:00+01:00  30.00   6.82  9.89   4.76  4003

Columna "fecha" tiene nulos: No - Nº: 0
Columna "G(i)" tiene nulos: No - Nº: 0
Columna "H_sun" tiene nulos: No - Nº: 0
Columna "T2m" tiene nulos: No - Nº: 0
Columna "WS10m" tiene nulos: No - Nº: 0
Columna "id" tiene nulos: No - Nº: 0

Tipos de las columnas:
fecha     object
G(i)     float64
H_sun    float64
T2m      float64
WS10m    float64
id         int64
dtype: object

La columna 'fecha' es tipo object. Para manejarla la pasaremos a datetime


Tipos de las columnas:
fecha    datetime64[ns, UTC+01:00]
G(i)                       float64
H_sun                      float64
T2m                        float64
WS10m                      float64
id                           int64
dtype: object

                      fecha   G(i)  H_sun   T2m  WS10m    id
0 2015-01-01 09:09:00+01:00  95.01   6.78  2.07   0.28  4001
1 2015-01-01 09:09:00+01:00  93.01   6.76  1.24   0.07  4002
2 2015-01-01 09:09:00+01:00  30.00   6.82  9.89   4.76  4003

Tiene duplicados: No

ºC max: 22.45 - ºC min: -16.88 -> No hay ningúna medida que pueda indicar una mala toma

Fecha max: <pandas.core.indexes.accessors.DatetimeProperties object at 0x7efbbf4e9bd0> - Fecha min: <pandas.core.indexes.accessors.DatetimeProperties object at 0x7efbbf4e9bd0> -> No hay ningúna fecha que pueda indicar una mala toma

count: 2584890.0
mean: 6.53
std: 4.64
min: -16.88
25%: 3.16
50%: 6.64
75%: 9.9
max: 22.45